### PR TITLE
Add a .rst example

### PR DESCRIPTION
**Pull request by nedbat**
Python projects like to use ReStructured Text.

### CODE REVIEW

**Comment by nedbat** [comment]
Good thing you asked for a syntax example, because I was missing a colon! I've fixed it here, and made an example you can see: https://github.com/nedbat/ColorWall

**Comment by nedbat** [comment]
is this repo now unmaintained? :)

**Comment by nedbat** [comment]
unmaintained repo is unmaintained

sad

**Comment by potch** [comment]
@nedbat maintained, but not _well_ maintained...

I'm happy to merge this, but am admittedly rather lazy- can you resolve the merge conflicts?

**Comment by nedbat** [comment]
Cool, done. :)

**Pull request merged**
